added run command added DSN option force on destroy relative to absolute paths params check

diff --git a/pg_sandbox b/pg_sandbox
--- a/pg_sandbox
+++ b/pg_sandbox
@@ -4,35 +4,20 @@
 # Output arguments to STDERR.
 #######################################
 print_error() {
-  echo "[ERROR] $*" >&2
+  echo "Error: $*" >&2
 }
 
 #######################################
-# Read default values for variables from an environment file.
-#   - If there is an environment file present in the current working directory, use it first.
-#   - If there is an environment file defined by $PG_SBOX_ENV_FILE, use it to override those values.
-#       $PG_SBOX_ENV_FILE is defined as ${PG_SBOX_DIR}/pg_sandbox.env by default.
+# If $PG_SBOX_DIR is a relative path, change it to an absolute path.
 #######################################
-read_variables_from_env_file() {
-  [[ -f ./pg_sandbox.env ]] && source ./pg_sandbox.env
-  [[ -f ${PG_SBOX_ENV_FILE} ]] && source ${PG_SBOX_ENV_FILE}
-}
-
-#######################################
-# Write values for variables to an environment file.
-#   $PG_SBOX_ENV_FILE is defined as ${PG_SBOX_DIR}/pg_sandbox.env by default.
-#######################################
-set_environment_file() {
-  mkdir -p `dirname $PG_SBOX_ENV_FILE`
-  echo PG_SBOX_SANDBOX_HOME="${PG_SBOX_SANDBOX_HOME}" > $PG_SBOX_ENV_FILE
-  echo PG_SBOX_BIN="${PG_SBOX_BIN}" >> $PG_SBOX_ENV_FILE
-  echo PG_SBOX_DBNAME="${PG_SBOX_DBNAME}" >> $PG_SBOX_ENV_FILE
-  echo PG_SBOX_DIR="${PG_SBOX_DIR}" >> $PG_SBOX_ENV_FILE
-  echo PG_SBOX_DATADIR="${PG_SBOX_DATADIR}" >> $PG_SBOX_ENV_FILE
-  echo PG_SBOX_LOG="${PG_SBOX_LOG}" >> $PG_SBOX_ENV_FILE
-  echo PG_SBOX_HOST="${PG_SBOX_HOST}" >> $PG_SBOX_ENV_FILE
-  echo PG_SBOX_PORT="${PG_SBOX_PORT}" >> $PG_SBOX_ENV_FILE
-  echo PG_SBOX_USER="${PG_SBOX_USER}" >> $PG_SBOX_ENV_FILE
+check_absolute_path() {
+  # If relative path is "./" or "."
+  if [[ ${PG_SBOX_DIR} == "./" ]] || [[ ${PG_SBOX_DIR} == "." ]]; then
+    PG_SBOX_DIR=`pwd`
+  # Else if relative path is "./path/to/dir"
+  elif [[ ${PG_SBOX_DIR} =~ ^./(.*) ]]; then
+    PG_SBOX_DIR=`pwd`"/""${BASH_REMATCH[1]}"
+  fi
 }
 
 #######################################
@@ -45,6 +30,46 @@ check_variables_defined() {
     print_error "For usage see $(basename "$0") --help"
     exit 1
   }
+
+  check_absolute_path
+}
+
+#######################################
+# Read default values for variables from an environment file.
+#   - If there is an environment file present in the current working directory, use it first.
+#   - If there is an environment file defined by $PG_SBOX_ENV_FILE, use it to override those values.
+#       $PG_SBOX_ENV_FILE is defined as ${PG_SBOX_DIR}/pg_sandbox.env by default.
+#######################################
+read_variables_from_env_file() {
+  [[ -f ./pg_sandbox.env ]] && source ./pg_sandbox.env
+  [[ -f ${PG_SBOX_ENV_FILE} ]] && source ${PG_SBOX_ENV_FILE}
+
+  check_absolute_path
+}
+
+#######################################
+# Write values for variables to an environment file.
+#   $PG_SBOX_ENV_FILE is defined as ${PG_SBOX_DIR}/pg_sandbox.env by default.
+# There is one caveat when relative paths are used, since this file will be written to in the
+# $PG_SBOX_ENV_FILE top level directory, which is $PG_SBOX_DIR, and the relative path may not
+# apply anymore once these variables are read. To workaround this, we transform them to absolute
+# paths instead.
+#######################################
+set_environment_file() {
+  if [ -f "${PG_SBOX_ENV_FILE}" ]; then
+    print_error "There is already a pg_sandbox.env file in ""${PG_SBOX_DIR}"
+    print_error "To avoid potentially overriding a previous sandbox environment, we will now exit."
+    exit 1
+  fi
+  mkdir -p "${PG_SBOX_DIR}"
+  echo PG_SBOX_BIN="${PG_SBOX_BIN}" >> $PG_SBOX_ENV_FILE
+  echo PG_SBOX_DBNAME="${PG_SBOX_DBNAME}" >> $PG_SBOX_ENV_FILE
+  echo PG_SBOX_DIR="${PG_SBOX_DIR}" >> $PG_SBOX_ENV_FILE
+  echo PG_SBOX_DATADIR="${PG_SBOX_DATADIR}" >> $PG_SBOX_ENV_FILE
+  echo PG_SBOX_LOG="${PG_SBOX_LOG}" >> $PG_SBOX_ENV_FILE
+  echo PG_SBOX_HOST="${PG_SBOX_HOST}" >> $PG_SBOX_ENV_FILE
+  echo PG_SBOX_PORT="${PG_SBOX_PORT}" >> $PG_SBOX_ENV_FILE
+  echo PG_SBOX_USER="${PG_SBOX_USER}" >> $PG_SBOX_ENV_FILE
 }
 
 #######################################
@@ -53,7 +78,7 @@ check_variables_defined() {
 print_help() {
   cat <<EOHELP
 Usage:
-    $(basename "$0") [OPTIONS] COMMAND
+    $(basename "$0") [OPTIONS] COMMAND [OTHER_OPTIONS]
 
 Commands:
     create             initialize the PostgreSQL instance, and start it
@@ -67,9 +92,11 @@ Commands:
     use                run the psql client. All arguments after "use" are sent directly to psql
 
 Options:
+    -a, --add-dsn      Add DSN (host, port and user) to the binary used with the "run" command
     -b, --bin          PostgreSQL binary directory to use with the sandbox environment
     -d, --dbname       database name (default: postgres)
     -D, --datadir      data directory to use within the sandbox directory (default: \${PG_SBOX_DIR}/data)
+    -f, --force        don't ask when removing the sandbox directory
     -?, --help         print this message and exit
     -h, --host         hostname or IP address to use with commands (default: 127.0.0.1)
     -l, --log          PostgreSQL server log file (default: )
@@ -80,14 +107,15 @@ Options:
 Example #1:
     $(basename "$0") -b /opt/postgresql/13/bin -s ./pg_13/ create
     $(basename "$0") -b /opt/postgresql/13/bin -s ./pg_13/ use
-    $(basename "$0") -b /opt/postgresql/13/bin -s ./pg_13/ use -e "SELECT 1"
+    $(basename "$0") -b /opt/postgresql/13/bin -s ./pg_13/ use -e "SELECT * FROM test.t1 LIMIT 10"
     $(basename "$0") -b /opt/postgresql/13/bin -s ./pg_13/ destroy
 
 Example #2:
     $(basename "$0") -b /opt/postgresql/13/bin -s ./pg_13/ setenv
     cd ./pg_13/
     $(basename "$0") create
-    $(basename "$0") use
+    $(basename "$0") -a run createdb test
+    $(basename "$0") use -d test
     $(basename "$0") stop
 
 EOHELP
@@ -97,7 +125,7 @@ EOHELP
 # Main function to run commands after being parsed.
 #######################################
 run_commands() {
-  # Check if minimum amount of defined variables is set
+  # Check if the minimum needed amount variables are set
   check_variables_defined
 
   # Command execution
@@ -113,7 +141,9 @@ run_commands() {
 
   if [[ "${PG_SBOX_COMMAND}" == "restart" ]]; then
     echo "Restarting server..."
-    ${PG_SBOX_BIN}/pg_ctl restart -D ${PG_SBOX_DATADIR} -mf
+    #${PG_SBOX_BIN}/pg_ctl restart -D ${PG_SBOX_DATADIR} -mf
+    ${PG_SBOX_BIN}/pg_ctl stop -D ${PG_SBOX_DATADIR} -mf
+    ${PG_SBOX_BIN}/pg_ctl start -D ${PG_SBOX_DATADIR} -o "-p ${PG_SBOX_PORT}" -l ${PG_SBOX_LOG}
   fi
 
   if [[ "${PG_SBOX_COMMAND}" == "use" ]]; then
@@ -135,8 +165,19 @@ run_commands() {
   if [[ "${PG_SBOX_COMMAND}" == "destroy" ]]; then
     echo "Stopping server..."
     ${PG_SBOX_BIN}/pg_ctl stop -D ${PG_SBOX_DATADIR} -mi
-    echo "Deleting sandbox directory..."
-    rm -rf ${PG_SBOX_DIR}
+    if [[ "${PG_SBOX_FORCE}" -eq 1 ]]; then
+      echo "Deleting sandbox directory..."
+      rm -rf ${PG_SBOX_DIR}      
+    else
+      echo -n "Do you want to remove ${PG_SBOX_DIR}? [y/N] "
+      read do_remove
+      if [[ "${do_remove}" == "y" ]] || [[ "${do_remove}" == "Y" ]]; then
+        echo "Deleting sandbox directory..."
+        rm -rf ${PG_SBOX_DIR}
+      else
+        echo "Skipping sandbox directory removal."
+      fi
+    fi
   fi
 
   if [[ "${PG_SBOX_COMMAND}" == "setenv" ]]; then
@@ -144,9 +185,22 @@ run_commands() {
     # for pg_sandbox to work without having to manually set them
     set_environment_file
   fi
+
+  if [[ "${PG_SBOX_COMMAND}" == "run" ]]; then
+    # This will run the first argument as binary (under the defined PG_SBOX_BIN directory)
+    # It will pass all other arguments as arguments for that binary
+    PG_SBOX_EXEC="${1}"
+    shift 1
+    if [[ "${PG_SBOX_ADD_DSN}" -eq 1 ]]; then
+      "${PG_SBOX_BIN}"/"${PG_SBOX_EXEC}" -h "${PG_SBOX_HOST}" -p "${PG_SBOX_PORT}" -U "${PG_SBOX_USER}" $@
+    else
+      "${PG_SBOX_BIN}"/"${PG_SBOX_EXEC}" $@
+    fi
+  fi
 }
 
 # Some needed defaults, that can be overridden
+PG_SBOX_DATADIR='data'
 PG_SBOX_DBNAME='postgres'
 PG_SBOX_HOST='127.0.0.1'
 PG_SBOX_PORT=5432
@@ -158,6 +212,11 @@ read_variables_from_env_file
 # Parse arguments and commands (this may override some values defined in env files!)
 while (( "$#" )); do
   case "$1" in
+    -a|--add-dsn)
+      PG_SBOX_ADD_DSN=1
+      shift 1
+      ;;
+
     -b|--bin)
       PG_SBOX_BIN=$2
       shift 2
@@ -169,8 +228,13 @@ while (( "$#" )); do
       ;;
 
     -D|--datadir)
-      PG_SBOX_DATADIR=$2
+      PG_SBOX_DATADIR=${PG_SBOX_DIR}/$2
       shift 2
+      ;;
+
+    -f|--force)
+      PG_SBOX_FORCE=1
+      shift 1
       ;;
 
     -h|--host)
@@ -179,6 +243,9 @@ while (( "$#" )); do
       ;;
 
     -l|--log)
+      #TODO: check bug with paths
+      #      this will happen with all, so we'll need to make it using variables for all
+      #      and make it so it is immutable, no matter the order in which they are used
       PG_SBOX_LOG=$2
       shift 2
       ;;
@@ -190,8 +257,9 @@ while (( "$#" )); do
 
     -s|--sandbox-dir)
       PG_SBOX_DIR=$2
+      check_absolute_path
       PG_SBOX_ENV_FILE=${PG_SBOX_DIR}/pg_sandbox.env
-      PG_SBOX_DATADIR=${PG_SBOX_DIR}/data/
+      PG_SBOX_DATADIR=${PG_SBOX_DIR}/${PG_SBOX_DATADIR}/
       PG_SBOX_LOG=${PG_SBOX_DATADIR}/server.log
       shift 2
       ;;
@@ -216,7 +284,7 @@ while (( "$#" )); do
       ;;
 
 # Parse commands
-    start | stop | restart | use | init | create | destroy | setenv)
+    start | stop | restart | run | use | init | create | destroy | setenv)
       PG_SBOX_COMMAND=$1
       shift 1
       break
